In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
l=np.zeros((3,4))
l

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:

l=np.ones((3,5))
l

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
l=np.full((4,4),7)
l

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [10]:
l=np.eye(5)
l

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(1,10,2) # not include 10

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0,2,10) # equaly space 

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [23]:
arr=np.array([1.2,2.3,3.4],dtype=np.float32)
arr.dtype
arr

array([1.2, 2.3, 3.4], dtype=float32)

# indexing and slicing


In [29]:
l=list(range(15))
arr=np.array(l).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
arr=arr.flatten()

In [31]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# slicing does not return copy it return view and changes in slice effect the original array beacuse numpy wants to save memory

# practice

In [35]:
# create a 3*3 array filled with random numbers and print its shape
a=np.random.randint(1,100,size=9)
a=a.reshape(3,3)
print(a,a.shape)

[[93 17  7]
 [97 36 85]
 [92 75 41]] (3, 3)


In [51]:
# convert an array of floats[1.1,2.2,3.3] into integers

a=np.array([1.1,2.2,3.3],dtype=np.int32)
# a.dtype=np.int32
print(a)

[1 2 3]


In [56]:
# use fancy indexing
a=np.arange(1,10)
print(a)
b=np.arange(1,9,2)
a[b]

[1 2 3 4 5 6 7 8 9]


array([2, 4, 6, 8])

In [61]:
# Reshape 1D array if size 9 into a 3*3 matrix
a =np.arange(9)
a=a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
a=np.arange(2,100,5)
a=a[a>50]
a


array([52, 57, 62, 67, 72, 77, 82, 87, 92, 97])