# MULTIDIMENSION ARRAY

In [3]:
import numpy as np
arr= np.arange(1,10,1)
arr= arr.reshape(3,3)
arr



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [10]:
arr[1:3 , 0:3]

array([[4, 5, 6],
       [7, 8, 9]])

# Broad casting